x-shared-settings: &shared-settings
  volumes:
    #host-path:container-path
    - ~/Desktop:/shared 
  environment:
    - REDIS_CONNECTION=redis
    - BASE_PATH=/shared
    - OUTPUT_PATH=/shared
    - TMP_PATH=/shared/tmp

services:

  coordinator:
    build: ./Coordinator/
    container_name: coordinator
    stdin_open: true
    depends_on:
      redis:
        condition: service_healthy
    <<: *shared-settings

  mapper-worker:
    build: ./Mapper/
    depends_on:
      - coordinator
    <<: *shared-settings
  
  reducer-worker:
    build: ./Reducer/
    depends_on:
      - coordinator
    <<: *shared-settings

  redis:
    image: redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
