FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /source

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -o /app

FROM mcr.microsoft.com/dotnet/runtime:9.0

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT  ["dotnet", "Coordinator.dll"]
